### ISSUE TITLE
Client side

### ISSUE THREAD

**Issue by ThunderGemios10** [PlitherProject/Plither#3]
You should probably not develop a client side software.. This is illegal .

**Comment by Ciao121** [comment]
ThunderGemios10, I cannot find any terms on slither.io . Did you find them?

**Comment by ThunderGemios10** [comment]
@Ciao121 What do you mean terms?

**Comment by Ciao121** [comment]
@ThunderGemios10, Terms of use... licensing. I couldn't find anything on slither.io. It could also be not illegal to develop a client side sofwtare. Or it could be illegal to use the existing source code but not writing one from scratch. It's depends on what license is used. But as I said I didn't find anything about this.

**Comment by ThunderGemios10** [comment]
@Ciao121 It is quite obvious.. and a common knowledge.. That developing a client side clone of Slither.io is quite illegal.. This also applies to Agar.io

**Comment by ThunderGemios10** [comment]
@Ciao121 Also, Slither.io's license is All Rights Reserved..

**Comment by Ciao121** [comment]
@ThunderGemios10 
I can't find "All Rights Reserved" anywhere on slither.io. Agar.io was complaining about clients because those was made **copying** their code. It's not illegal to make a cient (otherways nobody could make a new web client). It **can be** illegal to use other's code to make a client. This depends on the license applied (and I can't find out what licenseis applied to slither.io).
Anyway if someoune found out the licensing file it's welcome here to clarify this.

**Comment by ThunderGemios10** [comment]
@Ciao121 Yes, But regardless making a client clone is illegal and it still uses Slither.io's assets, Unless of course every asset is fan-made.

**Comment by Ciao121** [comment]
@ThunderGemios10 , so, someone can write a client from scratch :) ehehhe

**Comment by ThunderGemios10** [comment]
@Ciao121 Writing a client from scratch is writing a new game from scratch.. Beats the whole point of "Slither Client"
